### PR TITLE
Adding Podspec

### PR DESCRIPTION
**Pull request by rdougan**
Thanks for the library.

You'll need to make a tag for the release - but otherwise it is good to go.

### CODE REVIEW

**Comment by lhecker** [comment]
First: I personally prefer git submodules more than pods, so I might have made a mistake or something, since I've never used it before.
You had a type in the repo URL with `https://github.com/lhecker/NSLabel.gif` (i.e.: .gi**f**).
I pushed a fix, added the tag and pushed the version to the pods trunk (?).

Anyhow: Thanks for your contribution! :smiley:

**Comment by rdougan** [comment]
Great. I just verified that it works.

I will add the podspec to the (horrible) specs repo (https://github.com/CocoaPods/Specs) so it can be installed without a direct GitHub URL.

**Comment by lhecker** [comment]
Shouldn `pods trunk push` do that already? Because I did create that file: https://github.com/CocoaPods/Specs/blob/master/Specs/NSLabel/1.0.0/NSLabel.podspec.json

**Comment by rdougan** [comment]
Oh awesome - I didn't know that was available. Much quicker..

**Comment by lhecker** [comment]
I used that guide: https://guides.cocoapods.org/making/getting-setup-with-trunk.html

Interestingly pods really has the usual downsides of the ruby community... :confused: 
Nowhere in the docs it was mentioned what the _Unable to find the `master` repo._ error means. Turns out that after installing pod and using it it won't initialize the local "cache". Running `pod spec lint` manually fixed it. Interestingly (N° 2) the docs say that `pod spec lint` should be run automatically if you use `pods trunk push`... :expressionless:

**Pull request merged**
